### ISSUE TITLE
Any plan to add new hardware wallet?

### ISSUE THREAD

**Issue by aaroninks** [TronLink/tronlink-extension-core#10]
Hey TronLink Team,

Aaron here from the Keystone crew. We're all about creating cutting-edge open-source hardware wallets over at Keystone. You can check out [our site](https://keyst.one/) for more info if you’d like. Just wanted to ask if you have any plans for adding new hardware wallet support? We've got a bunch of Keystone users who are eager for a TronLink integration. Let me know what you think!

Best,
Aaron

**Comment by tronlinkdev** [comment]
Hi. Thanks for reaching out. As discussed, we will evaluate more hardware wallet to be supported at next FY planning.
