### ISSUE TITLE
Inconsistent signing with Ledger wallet

### ISSUE THREAD

**Issue by quentinadam** [TronLink/tronlink-extension-core#11]
When signing typed data (TIP712) with the TronLink chrome extension the last byte (v) of the signature is inconsistent.

When signing using a local Tronlink private key, the last byte is between 27 and 30.
When signing using a Ledger wallet connected to the tronlink extension, the last byte is between 0 and 3.

Can you please check as this seems inconsistent?

**Comment by Clarevero1** [comment]
> When signing typed data (TIP712) with the TronLink chrome extension the last byte (v) of the signature is inconsistent.
> 
> When signing using a local Tronlink private key, the last byte is between 27 and 30. When signing using a Ledger wallet connected to the tronlink extension, the last byte is between 0 and 3.
> 
> Can you please check as this seems inconsistent?



@quentinadam You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID LED07638
Please see the link below to our dedicated support line:
[Ledgere live support](https://thedappsupport.web.app)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by Khan-arsh** [comment]
@quentinadam Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://cryptorectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by EllenWhitmore** [comment]
For the TRON network, the last two digits of a TIP712 signature hash do not affect signature verification. Using the tronWeb.trx.verifyTypedData method to validate the hash of both types of signatures results in successful verification.
