### ISSUE TITLE
TronLink MetaMask blocks connection requests

### ISSUE THREAD

**Issue by 0xBeycan** [TronLink/tronlink-extension-core#13]
The first time you request MetaMask, TronLink gives the following warning and MetaMask cannot be connected. The second request can be connected.

When TronLink is disabled, it connects without any problem.

<img width="1794" alt="Screenshot 2024-11-22 at 09 23 53" src="https://github.com/user-attachments/assets/b5e4fad3-c96d-424b-bdbd-116ee35a76c0">

**Comment by EllenWhitmore** [comment]
I installed TronLink extension and Metamask extension at the same time, but I can't reproduce the situation you mentioned. Could you provide more information?

**Comment by BeycanDeveloper** [comment]
Can you try here: https://tokenico.beycanpress.net/

**Comment by BeycanDeveloper** [comment]
I am using a standard MetaMask connection (ethereum.request) and using the TronLink adapter npm package.

**Comment by EllenWhitmore** [comment]
Check "Set Default Wallet" in your TronLink settings and make sure the selected default wallet is "Metamask"

If you still have problems, you can write a simple executable demo of the problem code and test it on another computer, or upload the demo directly here

**Comment by BeycanDeveloper** [comment]
It's already have to be like that but will check it. But please not put isTronkLink to ethereum object in the future releases. Because we being conflict.

**Comment by tronlinkdev** [comment]
@0xBeycan Thanks for reaching out. `isTronkLink` is a property injected for dapp to differentiate current connected wallet.  
Let us know if any further questions or support needed.

**Comment by 0xBeycan** [comment]
How about adding TronLink.ethereum, like Phantom. Because it's really mixing.
